### ISSUE TITLE
Lock aspect ratio

### ISSUE THREAD

**Issue by AGulev** [subsoap/defos#38]
I need to lock minimum aspect ration as  of the window (on windows) 4:3 and maximus as 16:9. 
Do somebody have some ideas how I can do this using DefOs?

**Comment by subsoap** [comment]
It should be able to be done on Windows without any DefOS changes. What you have to do is check the current window size and make sure that it conforms to the min/max and if not then it will resize the window so that it does. That kind of function could be added too. Lots of games do this like Hearthstone.

**Comment by AGulev** [comment]
We don't know position of the window, and can't set resolution without position.
But it's not a problem. Now I try to find way use lpfnWndProc callback and write this method fully on DefOS side.

If I can't do this, I add get_position method and make it using this method.

**Comment by chaosddp** [comment]
If you want to use WndProc callback,  you can have a try with SetWindowLongPtr to replace current WndProc with you own. as i think that Defold already hooked it.

**Comment by chaosddp** [comment]
@AGulev we have a  lpfnWndProc callback implement now on #39, you can try to handle your message in it.

**Comment by AGulev** [comment]
@chaosddp cool Thank you!

**Comment by AGulev** [comment]
Now developer can make all calculation in lua using defos.get_window_size() and defos.set_window_size().
